version: '3'

tasks:
  deps:
    desc: Install development requirements
    sources:
      - requirements-dev.txt
    generates:
      - .venv/.freeze
    cmds:
      - pip install -r requirements-dev.txt
      - pip freeze > .venv/.freeze

  fmt:
    desc: Format code
    cmds:
      - black src

  lint:
    desc: Lint code, excluding the lib directory
    cmds:
      - flake8 --exclude=.venv,lib --ignore=E501

  deploy:
    desc: Deploy code to the ESP32
    deps:
      - deps
    vars:
      USB_PORT:
        # Get the USB port of the ESP32
        sh: esptool.py read_flash_status | grep -oE "/dev/ttyUSB.+?"
    dir: src
    cmds:
      - ampy -p {{.USB_PORT}} put

  get-micropython-image:
    desc: Get the latest MicroPython image
    status:
      - test -f micropython/ESP32_GENERIC-20241129-v1.24.1.bin
    cmds:
      - mkdir -p micropython
      - wget https://micropython.org/resources/firmware/ESP32_GENERIC-20241129-v1.24.1.bin -O micropython/ESP32_GENERIC-20241129-v1.24.1.bin

  flash-micropython:
    deps:
      - get-micropython-image
    cmds:
      - esptool.py --chip esp32 --baud 460800 write_flash -ez 0x1000 micropython/ESP32_GENERIC-20241129-v1.24.1.bin

  help:
    desc: Show help
    cmds:
      - task --list