version: '3'

tasks:
  deps:
    desc: Install development requirements
    cmds:
      - pip install -r requirements-dev.txt

  fmt:
    desc: Format code
    cmds:
      - black src

  lint:
    desc: Lint code, excluding the lib directory
    cmds:
      - flake8 --exclude=.venv,lib --ignore=E501

  deploy:
    deps:
      - install-dev
    cmds:
      - ampy -p /dev/ttyUSB0 put src/*

  get-micropython-image:
    desc: Get the latest MicroPython image
    status:
      - test -f micropython/ESP32_GENERIC-20241129-v1.24.1.bin
    cmds:
      - mkdir -p micropython
      - wget https://micropython.org/resources/firmware/ESP32_GENERIC-20241129-v1.24.1.bin -O micropython/ESP32_GENERIC-20241129-v1.24.1.bin

  flash-micropython:
    deps:
      - get-micropython-image
    cmds:
      - esptool.py --chip esp32 --baud 460800 write_flash -ez 0x1000 micropython/ESP32_GENERIC-20241129-v1.24.1.bin

  help:
    desc: Show help
    cmds:
      - task --list